config/routes.rb
Wipgit::Application.routes.draw do

  resources :repos do
    controller "wip" do
      get "wip/:wip_date", action: :on, as: :wip_ondate
      get "wip/today", action: :today
    end
  end

  get "me" => "me#show"

  resource :session, only: [:new, :create, :destroy]

  root to: 'me#show'

end

app/models/commit.rb
class Commit

  attr_accessor :url, :sha, :message, :committer_name, :commit_date, :avatar_url

  def initialize(attributes)
    attributes.each do |name, value|
      self.send("#{name}=", value)
    end
  end

  def self.from_github(octokit_hash)
    attributes = {}
    attributes[:url] = octokit_hash[:url]
    attributes[:sha] = octokit_hash[:sha]
    attributes[:message] = octokit_hash[:commit][:message]
    attributes[:committer_name] = octokit_hash[:commit][:committer][:name]
    attributes[:commit_date] = DateTime.parse(octokit_hash[:commit][:committer][:date])
    attributes[:avatar_url] = octokit_hash[:committer][:avatar_url]
    Commit.new(attributes)
  end

  def self.from_local(grit_commit)
    attributes = {}
    attributes[:sha] = grit_commit.sha
    attributes[:message] = grit_commit.message
    attributes[:committer_name] = grit_commit.committer.name
    attributes[:commit_date] = grit_commit.date
    attributes[:avatar_url] = Gravatar.new(grit_commit.committer.email).image_url
    Commit.new(attributes)
  end

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :uri, :user_id

  validates_presence_of :uri, :user

  def commits_on(date)
    CommitFetcher.new(self, date).commits
  end

  def github?
    !!(self.uri =~ /^\w+\/\w+$/)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :password_digest, :username

  has_many :repos


  def self.authenticate(username, password)
    user = User.find_by_username(username)
    unless user
      raise "No user with such username"
    end

    unless user.authenticate(password)
       raise "password invalid"
    end
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :check_authentication

  def current_user
    User.find(session[:user_id])
  end

  def check_authentication
    unless session[:user_id]
      redirect_to new_session_url
    end
  end
end

app/controllers/me_controller.rb
class MeController < ApplicationController

  def show
    @user = User.find(session[:user_id])
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  respond_to :json

  def show
    respond_with Repo.find(params[:id])
  end

  def index
    respond_with current_user.repos
  end

  def update
    @repo = Repo.find(params[:id])
    respond_with @repo.update(params[:repo])
  end

  def create
    respond_with Repo.create!(params[:repo])
  end

  def destroy
    respond_with Repo.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :check_authentication, :only => [:new, :create]

  def new
  end

  def create
    session[:user_id] = User.authenticate(params[:username], params[:password]).id
    flash[:notice] = "You're in!"
    redirect_to me_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wip_controller.rb
class WipController < ApplicationController

  before_filter :current_repo

  def today
    @asked_date = DateTime.now
    @commits = @repo.commits_on(@asked_date)
    render :calendar
  end

  def on
    @asked_date = DateTime.parse(params[:wip_date])
    @commits = @repo.commits_on(@asked_date)
    render :calendar
  end

  private

  def current_repo
    @repo ||= Repo.find(params[:repo_id])
  end
end

app/controllers/wips_controller.rb
class WipsController < ApplicationController

  before_filter :load_repo

  def show
    @commits = Octokit.commits("#{@repo.name}/#{@repo.project}")
  end

  def today
    @asked_date = DateTime.now
    @commits = @repo.commits_on(@asked_date)
    render :calendar
  end

  def on
    @asked_date = DateTime.parse(params[:wip_date])
    @commits = @repo.commits_on(@asked_date)
    render :calendar
  end

  private

  def load_repo
    @repo = Repo.find(params[:repo_id])
  end
end

app/helpers/wips_helper.rb
module WipsHelper

  def display_day_before(datetime)
    datetime.yesterday.strftime("%Y-%m-%d")
  end

  def display_date(datetime)
    datetime.strftime("%Y-%m-%d")
  end

  def display_time(datetime)
    datetime.strftime("%H:%m")
  end

  def display_day_after(datetime)
    datetime.tomorrow.strftime("%Y-%m-%d")
  end

end

app/views/layouts/_header.html.haml
%header
  - if session[:user_id]
    = link_to 'Sign out', session_path, method: :delete
  - else session[:user_id]
    = link_to 'Sign in', new_session_path

app/views/layouts/_notifications.html.haml
- if notice.present?
  .notifications
    =notice
- if alert.present?
  .alerts
    =alert

app/views/layouts/application.html.haml
!!! 5
%html(ng-app="Wipgit")
%head
  %title Wipgit
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body

  = render 'layouts/header'
  = render 'layouts/notifications'
  = yield

app/views/me/show.html.haml
%h1
  Welcome #{@user.username}

%div(ng-controller="ReposCtrl")
  %ul
    %li(ng-repeat="repo in repos")
      {{repo.uri}}
      =link_to "see today"

%h2
  =link_to "Your repos", repos_path

app/views/repos/edit.html.haml
%h1
  Edit repo

= semantic_form_for @repo do |f|
  = f.inputs :name, :project
  = f.input :user_id, as: :hidden
  = f.actions

app/views/repos/index.html.haml
%h2
  Your repos
%ul
  - @repos.each do |repo|
    %li #{repo.uri}
    = link_to "wip", today_repo_wip_path(repo)
    = link_to "delete", repo_path(repo), method: :delete
= link_to "New repo", new_repo_path

app/views/repos/new.html.haml
%h1
  New repo

= semantic_form_for @repo do |f|
  = f.inputs :name, :project
  = f.input :user_id, as: :hidden
  = f.actions

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wip/calendar.html.haml
%div#commits-container
  %section#commits-before.commits
    %h1
      Before
    - day_before_as_string = display_day_before(@asked_date)
    = link_to "Day before (#{day_before_as_string})", repo_wip_ondate_path(@repo, day_before_as_string)

  %section#current-commits.commits
    %h1
      Current #{display_date(@asked_date)}
    - @commits.each do |commit|
      .commit
        .committer
          %img{src: "#{commit.avatar_url}"}
          =commit.committer_name
        .infos
          .metadata
            =display_time(commit.commit_date)
            %a{href: commit.url} #{commit.sha}
          .message
            %pre #{commit.message}

  %section#commits-after.commits
    %h1
      After
    - day_after_as_string = display_day_after(@asked_date)
    = link_to "Day after (#{day_after_as_string})", repo_wip_ondate_path(@repo, day_after_as_string)

app/views/wip/on.html.haml
%ul
  - @commits.each do |commit|
    %li #{commit.commit.message} #{commit.commit.author.date}

app/views/wip/show.html.haml
%ul
  - @commits.each do |commit|
    %li #{commit.commit.message} #{commit.commit.author.date}

app/views/wips/calendar.html.haml
%div#commits-container
  %section#commits-before.commits
    %h1
      Before
    - day_before_as_string = display_day_before(@asked_date)
    = link_to "Day before (#{day_before_as_string})", ondate_repo_wip_path(@repo, day_before_as_string)

  %section#current-commits.commits
    %h1
      Current #{display_date(@asked_date)}
    - @commits.each do |commit|
      .commit
        .committer
          %img{src: "#{commit.avatar_url}"}
          =commit.committer_name
        .infos
          .metadata
            =display_time(commit.commit_date)
            %a{href: commit.url} #{commit.sha}
          .message
            %pre #{commit.message}

  %section#commits-after.commits
    %h1
      After
    - day_after_as_string = display_day_after(@asked_date)
    = link_to "Day after (#{day_after_as_string})", ondate_repo_wip_path(@repo, day_after_as_string)